import type { Prisma } from '@prisma/client';

export const profileSeedData = {
  name: 'Крайцер Глеб Геннадьевич',
  description:
    'Fullstack-разработчик с инженерным образованием и опытом в системном администрировании, связи, медиапроизводстве и веб-разработке. Специализируюсь на JavaScript/TypeScript, Python, React, Vue и Node.js. Применяю системное мышление и технический бэкграунд, чтобы разбираться в сложных системах и доводить задачи до рабочего результата.',
  githubUrl: 'https://github.com/Kraitcer',
  linkedinUrl: 'https://www.linkedin.com/in/gleb-kraitcer/',
  skills: {
    create: [
      'JavaScript',
      'TypeScript',
      'Python',
      'SQL',
      'HTML5',
      'CSS3',
      'Sass/SCSS',
      'React',
      'Redux',
      'Zustand',
      'React Query',
      'React Hook Form',
      'React DnD',
      'DnD Kit',
      'Vue.js',
      'Vue 3',
      'Nuxt',
      'Vite',
      'Pinia',
      'Vue Router',
      'vue3-virtual-scroller',
      'Bootstrap',
      'Element Plus',
      'Chakra UI',
      'unoCSS',
      'BEM',
      'Адаптивная верстка',
      'ApexCharts',
      'Node.js',
      'Express',
      'NestJS',
      'REST API',
      'GraphQL',
      'JWT',
      'EventSource',
      'Pyasic',
      'ООП',
      'Telegram Bot API',
      'ExcelJS',
      'Axios',
      'Luxon',
      'OpenCart',
      'MySQL',
      'MongoDB',
      'Prisma',
      'PostgreSQL',
      'Docker',
      'Nginx',
      'HTTPS',
      'Git',
      'npm',
      'Сетевое администрирование',
      'Adobe Photoshop',
      'Звукорежиссура и продакшн',
      'Видеомонтаж',
      'Менторство и обучение',
    ].map((name) => ({ name })),
  },
  experience: {
    create: [
      {
        company: 'Векус, ЦКТ, ООО',
        position: 'Fullstack-разработчик',
        period: 'Июнь 2023 - Август 2026',
        achievements: [
          'Разработал веб-приложение для мониторинга и удаленного управления ASIC-майнерами: SPA-интерфейс, backend-сервисы, MySQL и агентское ПО.',
          'Создал генератор Excel-отчетов по клиентам и площадкам с редактором премодерации данных.',
          'Автоматизировал учет клиентских балансов, начислений и списаний за обслуживание.',
          'Разработал аутентификацию, авторизацию и гибкую ролевую модель доступа.',
          'Создал систему уведомлений об отключениях и неисправностях с тикетами и Telegram-уведомлениями.',
          'Реализовал учет поломок, логистику, согласование ремонта и удаленное управление агентами.',
          'Усилил архитектуру кластерным распределением нагрузки и перенес REST API на Nest.js.',
          'Настроил HTTPS, Nginx и контейнеризацию в Docker.',
          'Разработал автономное Python-агентское ПО в формате standalone .exe со сбором логов.',
          'Выполнил рестайлинг интерфейса по макетам Figma и адаптивную верстку.',
        ],
      },
      {
        company: 'Ultima PRO Group',
        position: 'Инженер-монтажник',
        period: 'Декабрь 2021 - Февраль 2023',
        achievements: [
          'Обслуживал, подключал и диагностировал технологические системы МФК «Лахта Центр».',
          'Участвовал в монтаже студии звукозаписи, видеомонтажной, планетария и серверного комплекса обработки 8K-контента.',
          'Работал с проекционным, акустическим, световым и инженерным оборудованием, включая Dolby Atmos и DMX-512.',
          'Руководил двумя группами монтажников, контролировал материалы, приемку и качество работ.',
        ],
      },
      {
        company: 'Лаймикс',
        position: 'Системный администратор',
        period: 'Июль 2013 - Апрель 2015',
        achievements: ['Обслуживал ИТ-инфраструктуру предприятия.'],
      },
      {
        company: 'ООО «Бизнес-отель Карелия», хостел «Граффити»',
        position: 'Системный администратор',
        period: 'Ноябрь 2011 - Февраль 2013',
        achievements: ['Обслуживал ИТ-инфраструктуру предприятия.'],
      },
      {
        company: 'Subcoin Studio',
        position:
          'Звукоинженер, менеджер студии, ментор образовательных проектов',
        period: 'Декабрь 2017 - Декабрь 2022',
        achievements: [
          'Занимался звукорежиссурой, управлением студией и менторством образовательных проектов.',
        ],
      },
      {
        company: 'MusicMagTv',
        position: 'Продюсер',
        period: 'Май 2015 - Сентябрь 2018',
        achievements: [
          'Продюсировал медиапроекты для YouTube-канала MusicMagTv.',
        ],
      },
      {
        company: 'Media Broker',
        position: 'Контент-менеджер / верстальщик',
        period: 'Январь 2015 - Январь 2017',
        achievements: [
          'Разрабатывал и поддерживал страницы на HTML, JavaScript, CSS и OpenCart.',
        ],
      },
    ],
  },
  projects: {
    create: [
      {
        name: 'ASIC Miner Monitoring Platform',
        description:
          'Веб-приложение для мониторинга, отчетности и удаленного управления ASIC-майнерами.',
        url: 'https://vekus.ru',
      },
      {
        name: 'Redux App',
        description: 'Проект на React/Redux.',
        url: 'https://redux-app-tau.vercel.app',
      },
      {
        name: 'Game Hub',
        description: 'Веб-приложение на React для работы с каталогом игр.',
        url: 'https://game-hub-ten-peach.vercel.app',
      },
      {
        name: 'GitHub',
        description: 'Исходный код и другие проекты.',
        url: 'https://github.com/Kraitcer',
      },
    ],
  },
} satisfies Prisma.ProfileCreateInput;
